<?php

/**
 * Implements hook_theme().
 */
function address_email_blocks_theme($existing, $type, $theme, $path) {
  return [
    'address_email_blocks-address' => [
      'variables' => [],
      'template' => 'address-email-blocks-address',
    ],
    'address_email_blocks-email' => [
      'variables' => [],
      'template' => 'address-email-blocks-email',
    ],
    'address_email_blocks-telephone' => [
      'variables' => [],
      'template' => 'address-email-blocks-telephone',
    ],
  ];
}
